version: "3"
services:
  postgres:
    build:
      context: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres

  clientfly:
    build: wildfly
    ports:
      - 8080:8080
      - 9090:9090
    container_name: clientfly

  devfly:
    build:
      context: wildfly
      args:
        PROFILE: service
    ports:
      - 8081:8080
    container_name: devfly

  rabbitmq:
    build: ./rabbitmq
    ports:
      - 15672:15672
    container_name: rmq

  adminer:
    image: adminer
    ports:
      - 8082:8080
